apiVersion: v1
kind: ReplicationController # 定义RC
metadata:
  name: myweb # RC名
spec:
  replicas: 1 # 定义pod副本数
  selector:
    app: myweb # 标签选择器，RC作用于这类标签
  template: # pod模板
    metadata:
      labels:
        app: myweb # 定义标签
    spec:
      containers: # 定义pod容器
      - name: myweb # 容器名
        image: kubeguide/tomcat-app:v1 # 容器镜像
        ports:
        - containerPort: 8080 # 容器对外端口
        env:
        - name: MYSQL_SERVICE_HOST
          value: 'mysql' # 与服务名一致
        - name: MYSQL_SERVICE_PORT # 与服务对外端口一致
          value: '3306'
